title: Louis（Bigang）'s Homepage
page-top-title: Louis LIAO
top-section-bg-text: HK POLYU Applied Biology 
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
