title: Louis（Bigang）'s Homepage
page-top-title: Louis LIAO
top-section-bg-text: HK POLYU Applied Biology 
home-subtitle: BIGANG;|&LOUIS;比鋼
copyright-text: '&copy; bigang louis 2025-2026. All Rights Reserved.'
